export const GET_APARTMENTS = 'GET_APARTMENTS';
export const CREATE_APARTMENT = 'CREATE_APARTMENT';
export const GET_APARTMENT_ROOMS_BY_ID = 'CREATE_APARTMENT_BY_ID';
export const GET_ROOMS = 'GET_ROOMS';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID';

export const GET_BOOKINGS = 'GET_BOOKINGS';
export const GET_BOOKING_BY_ID = 'GET_BOOKING_BY_ID';

export const ERROR = 'ERROR';
