export const GET_APARTMENTS = 'GET_APARTMENTS';
export const CREATE_APARTMENTS = 'CREATE_APARTMENTS';
export const GET_APARTMENT_ROOMS_BY_ID = 'CREATE_APARTMENT_BY_ID';

export const ERROR = 'ERROR';
